### ISSUE TITLE
Oscar Roadmap

### ISSUE THREAD

**Issue by wbhart** [oscar-system/ComAlg.jl#4]
This is a roadmap of all issues people consider important or of high priority across the whole of the Oscar system.
Names are attached to the issues currently being worked on. They are in no particular order.

- Infrastructure
  - [X] Report type inference issues to Julia - @wbhart
  - [X] Continuous integration - @rbehrends 
  - [ ] Flint release, roadmap : https://github.com/wbhart/flint2/issues/517 - @wbhart 
  - [ ] Julia testsets
- AbstractAlgebra.jl, Nemo
  - [X] Modules over Euclidean domains - @wbhart 
  - [ ] iseuclidean, isdomain, etc. predicates in AbstractAlgebra
  - [ ] clean up left/right kernel/solve interface in AbstractAlgebra
  - [ ] Groups interface - @kalmarek @fieker @fingolfin 
  - [ ] Interface conformance testing @kalmarek 
  - [ ] Localisations of Z and K[x] in AbstractAlgebra/Nemo
- Singular, Singular.jl
  - [X] Nemo coefficient rings in Singular.jl @sebasguts @wbhart
  - [ ] Get tests passing on OSX
  - [ ] BinaryProvider for Singular.jl @wbhart @thofma @hannes14 
  - [ ] Make Singular.jl an official Julia package @wbhart
  - [ ] Remove execute from Singular library code - @steenpass 
  - [X] Parallel conversion of Singular multivariates to Factory and vice versa - @hannes14 
  - [X] Integrate Flint multivariates into Factory (ODK) - @hannes14 @tthsqe12
  - [ ] Fix memory leaks in Singular.jl due to CxxWrap usage (example please)
  - [ ] Subquotient modules for Singular.jl
  - [ ] Singular to Julia transpiler - @hannes14 @tthsqe12 @rfourquet
  - [ ] Access to Singular interpreter/libraries from Singular.jl - https://github.com/oscar-system/Singular.jl/pull/104 - @sebasguts @wbhart 
  - [ ] Wrap more Singular kernel functions in Singular.jl
  - [X] Automatically build documentation on GitHub pages @wbhart
- GAP, GAP.jl
  - [ ] BinaryProvider for GAP.jl @fingolfin 
  - [ ] High level interface for GAP.jl
  - [ ] GAP help available in Julia - https://github.com/oscar-system/GAP.jl/pull/251 - @ThomasBreuer @sebasguts
  - [ ] GAP REPL mode - https://github.com/oscar-system/GAP.jl/pull/225 - @sebasguts 
- Polymake, Polymayke.jl
  - [ ] High level interface for Polytopes: [OscarPolytope.jl](https://github.com/oscar-system/OscarPolytope.jl) @lkastner 
  - [ ] Polymake.jl on OSX @benlorenz 
- Oscar.jl
  - [ ] User documentation for Oscar.jl
  - [ ] Conversion functions between different matrix and polynomial types in Oscar.jl
  - [ ] Make all dependencies of Oscar.jl build with a single version of Julia - @sebasguts @wbhart
  - [ ] Import of chosen default functionality into Oscar.jl from other systems
      - This does not mean "using Hecke; using Nemo; using Singular", etc. It means importing only the required functionality, as the former is not expected to be possible.
- Unsorted
  - [ ] Finitely generated abelian groups - @fieker 
  - [X] Harmonise interface for Fin Gen Ab Gps and Fin Pres Mods over Euc Dom - @fieker @wbhart 
  - [ ] Embeddings of finite fields
  - [ ] Euc. domain interface, esp. for polys and matrices in AbstractAlgebra - @wbhart @fieker 
  - [ ] Rational functions over cyclotomic fields (requested by Frank and Thomas) - @wbhart @fieker @tthsqe12
  - [ ] Precompile some code for basic rings (e.g. Z, Z/pZ, Q, etc.) to avoid Jit overhead
  - [ ] Implement Julia map functionality for our types
  - [ ] Implement more of Julia's view/submatrix functionality where they make sense for our types
  - [ ] Decorated rings/modules (gradings, etc.)

**Comment by fingolfin** [comment]
@fieker @CarloSircana we (me and @sebasguts ) have been wondering what "High level interface for GAP.jl" is meant to be -- is that just a duplicate of the "Groups interface" entry, or something else? If so, could you please explain? Clearly we can't implement anything we don't know about :-)

**Comment by fieker** [comment]
On Wed, Jun 19, 2019 at 01:10:17AM -0700, Max Horn wrote:
> @fieker @CarloSircana we (me and @sebasguts ) have been wondering what "High level interface for GAP.jl" is meant to be -- is that just a duplicate of the "Groups interface" entry, or something else? If so, could you please explain? Clearly we can't implement anything we don't know about :-)

I am disappointed, you cannot read minds?

As far as I am concerned, the Group Interface is part of it, gap
possibly has more to offer...

**Comment by wbhart** [comment]
What @kalmarek and I had in mind for the Group Interface was a written document describing an interface to Groups in AbstractAlgebra and/or Oscar.

The high level interface for GAP.jl is an actual implementation of a layer on top of GAP.jl which makes the functionality in GAP available in a version that uses Julia naming conventions and paradigms, similar to what we have done with Singular.jl vs its libsingular module.

I am sure it will encompass parts of the Galois Groups interface @fieker has planned and certainly parts of the interface you guys have been working on. But note that the interface for Groups has to also encompass @kalmarek 's permutation groups (if possible) and @fieker 's finitely generated abelian groups, which are entirely in Julia. So the project is more than an interface layer to GAP.jl.

If everyone working on groups (I am not) think there is a better arrangement of what you guys are actually doing, please do rearrange this to reflect what you are actually doing.

**Comment by wbhart** [comment]
Moved to Oscar.jl.
